# Generated by Django 2.2.19 on 2022-09-11 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('FILE', 'файл'), ('FOLDER', 'папка')], max_length=6)),
                ('date', models.DateTimeField()),
                ('url', models.TextField(null=True)),
                ('size', models.PositiveIntegerField(null=True)),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Item')),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=255, null=True)),
                ('size', models.PositiveIntegerField(null=True)),
                ('date', models.DateField()),
                ('parentId', models.UUIDField(null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Item')),
            ],
        ),
    ]
